# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 23:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereplay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='match_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='match_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='num_entities',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalgame',
            name='num_turns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='legend_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
