# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160824_2333'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingreplayownership',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='pendingreplayownership',
            name='replay',
        ),
        migrations.RemoveField(
            model_name='pendingreplayownership',
            name='token',
        ),
        migrations.DeleteModel(
            name='PendingReplayOwnership',
        ),
    ]
