# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20160905_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereplay',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
