# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-11 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_gamereplay_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgameplayer',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Player name'),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='real_name',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Real name'),
        ),
    ]
