# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20160911_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgame',
            name='match_start',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
