# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20160919_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgame',
            name='scenario_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID from DBF/SCENARIO.xml or Scenario cache', null=True, verbose_name='Scenario ID'),
        ),
    ]
