# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20160922_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgame',
            name='digest',
            field=models.CharField(db_index=True, help_text='SHA1 of str(game_handle), str(server_address), str(lo1), str(lo2)', max_length=40, null=True),
        ),
    ]
