# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_globalgame_digest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='globalgameplayer',
            unique_together=set([('game', 'player_id')]),
        ),
    ]
