# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20160925_0548'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamereplay',
            unique_together=set([('global_game', 'client_handle', 'friendly_player_id', 'spectator_mode', 'reconnecting')]),
        ),
    ]
