# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20161002_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgameplayer',
            name='include_in_stats',
            field=models.BooleanField(default=True, verbose_name='The required has all required fields AND user settings allows stats'),
        ),
    ]
