# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hsreplaynet.packs.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booster_type', hsreplaynet.utils.fields.IntEnumField(choices=[(1, 'CLASSIC'), (2, 'GVG'), (3, 'TGT'), (4, 'OG')], validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.packs.models.BoosterType)])),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PackCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('premium', models.BooleanField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Card')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packs.Pack')),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='cards',
            field=models.ManyToManyField(through='packs.PackCard', to='cards.Card'),
        ),
        migrations.AddField(
            model_name='pack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='packcard',
            unique_together=set([('card', 'premium')]),
        ),
    ]
