# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='account_hi',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pack',
            name='account_lo',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='packcard',
            unique_together=set([]),
        ),
    ]
