# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import hsreplaynet.features.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'OFF'), (1, 'STAFF_ONLY'), (2, 'IN_PROGRESS'), (3, 'PUBLIC'), (4, 'AUTHORIZED_ONLY')], default=2, validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.features.models.FeatureStatus)])),
                ('read_only', models.BooleanField(default=False)),
            ],
        ),
    ]
