# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='creation_apikey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.APIKey'),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='is_test_data',
            field=models.BooleanField(default=False),
        ),
    ]
