# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160926_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='creation_apikey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.APIKey'),
        ),
    ]
