# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_delete_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeleteRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('delete_replay_data', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete_account_request',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='delete_replay_data',
        ),
        migrations.AddField(
            model_name='accountdeleterequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
