# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160712_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
