# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160918_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exclude_from_statistics',
            field=models.BooleanField(default=False),
        ),
    ]
