# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import hsreplaynet.uploads.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadevent',
            name='file',
            field=models.FileField(null=True, upload_to=hsreplaynet.uploads.models._generate_upload_path),
        ),
        migrations.AlterField(
            model_name='uploadevent',
            name='metadata',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadevent',
            name='upload_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
