# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import hsreplaynet.uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20160818_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadevent',
            name='type',
        ),
        migrations.AddField(
            model_name='uploadevent',
            name='attempts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadevent',
            name='descriptor',
            field=models.FileField(null=True, upload_to=hsreplaynet.uploads.models._generate_descriptor_path),
        ),
    ]
