# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hsreplaynet.uploads.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_uploadevent_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='test_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadevent',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='api.APIKey'),
        ),
        migrations.AlterField(
            model_name='uploadevent',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='games.GameReplay'),
        ),
        migrations.AlterField(
            model_name='uploadevent',
            name='status',
            field=hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'UNKNOWN'), (1, 'PROCESSING'), (2, 'SERVER_ERROR'), (3, 'PARSING_ERROR'), (4, 'SUCCESS'), (5, 'UNSUPPORTED'), (6, 'VALIDATION_ERROR')], default=0, validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.uploads.models.UploadEventStatus)]),
        ),
    ]
