# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import hsreplaynet.uploads.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20160824_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='uploadevent',
            name='status',
            field=hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'UNKNOWN'), (1, 'PROCESSING'), (2, 'SERVER_ERROR'), (3, 'PARSING_ERROR'), (4, 'SUCCESS'), (5, 'UNSUPPORTED'), (6, 'VALIDATION_ERROR'), (7, 'VALIDATING')], default=0, validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.uploads.models.UploadEventStatus)]),
        ),
    ]
