# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import hsreplaynet.uploads.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20160824_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='canary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadevent',
            name='status',
            field=hsreplaynet.utils.fields.IntEnumField(choices=[(0, 'UNKNOWN'), (1, 'PROCESSING'), (2, 'SERVER_ERROR'), (3, 'PARSING_ERROR'), (4, 'SUCCESS'), (5, 'UNSUPPORTED'), (6, 'VALIDATION_ERROR'), (7, 'VALIDATING'), (8, 'UNSUPPORTED_CLIENT')], default=0, validators=[hsreplaynet.utils.fields.IntEnumValidator(hsreplaynet.uploads.models.UploadEventStatus)]),
        ),
    ]
