# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20160919_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadevent',
            name='attempts',
        ),
    ]
