# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_remove_uploadevent_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='log_group_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadevent',
            name='log_stream_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadevent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
